---
- name: install gcc
  command: xcode-select --install creates=/usr/bin/gcc

# Assuming homebrew is already installed...
- name: update homebrew
  homebrew: update_homebrew=yes

- name: install homebrew taps
  homebrew_tap: tap={{ item }} state=present
  loop: "{{ homebrew.taps }}"

- name: install homebrew packages
  homebrew: name={{ item }} state=upgraded
  loop: "{{ homebrew.packages }}"

- name: install homebrew casks
  homebrew_cask: name={{ item }} state=installed
  loop: "{{ homebrew.casks }}"

# oh-my-zsh
- name: clone oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git
       dest=~/.oh-my-zsh
